# Generated by Django 6.1.1 on 2026-10-07 18:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0006_alter_membership_status'),
        ('scheduling', '0003_alter_booking_status'),
        ('tenancy', '0006_userprofile_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='description',
        ),
        migrations.AddField(
            model_name='booking',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='credits_used',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberships.membership'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.resource'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending / Reserved'), ('checked_in', 'Checked In (Waiting in Lobby)'), ('in_progress', 'In Session / Treatment'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='resource',
            name='credit_cost',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='resource',
            name='duration_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='resource',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.organization'),
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blood_pressure', models.CharField(blank=True, help_text='e.g. 120/80', max_length=20, null=True)),
                ('pulse_rate', models.IntegerField(blank=True, help_text='BPM', null=True)),
                ('temperature', models.CharField(blank=True, help_text='°F or °C', max_length=10, null=True)),
                ('oxygen_spo2', models.IntegerField(blank=True, help_text='SpO2 percentage', null=True)),
                ('chief_complaint', models.TextField(blank=True, help_text='Patient ki primary takleef')),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('doctor_signature', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_note', to='scheduling.booking')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_notes', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField(default='09:00:00')),
                ('end_time', models.TimeField(default='17:00:00')),
                ('break_start', models.TimeField(blank=True, null=True)),
                ('break_end', models.TimeField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.organization')),
            ],
            options={
                'unique_together': {('doctor', 'day_of_week')},
            },
        ),
        migrations.DeleteModel(
            name='BlackoutDate',
        ),
    ]
