# Generated by Django 6.1.1 on 2026-10-07 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0006_alter_membership_status'),
        ('scheduling', '0004_remove_resource_description_booking_doctor_and_more'),
        ('tenancy', '0007_remove_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='doctor',
        ),
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='credits_used',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='memberships.membership'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='scheduling.resource'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('canceled', 'Canceled')], default='confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='resource',
            name='credit_cost',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='resource',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='resource',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='tenancy.organization'),
        ),
        migrations.CreateModel(
            name='BlackoutDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(default='Maintenance / Holiday', max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackouts', to='tenancy.organization')),
            ],
        ),
        migrations.DeleteModel(
            name='ClinicalNote',
        ),
        migrations.DeleteModel(
            name='DoctorSchedule',
        ),
    ]
