# Generated by Django 6.1.1 on 2026-10-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_booking_doctor_alter_booking_status_clinicalnote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalnote',
            name='patient_notes',
            field=models.TextField(blank=True, help_text='Visible to patient'),
        ),
        migrations.AlterField(
            model_name='clinicalnote',
            name='private_notes',
            field=models.TextField(blank=True, help_text='Internal notes'),
        ),
    ]
