# Generated by Django 6.1.1 on 2026-10-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_alter_clinicalnote_patient_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalnote',
            name='patient_notes',
            field=models.TextField(blank=True, help_text='Prescription and diet visible to patient'),
        ),
        migrations.AlterField(
            model_name='clinicalnote',
            name='private_notes',
            field=models.TextField(blank=True, help_text='Confidential doctor remarks'),
        ),
    ]
