"""
Django settings for haus_platform project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

# from pathlib import Path
# # In your settings.py:
# import os

# # Console backend for local development (prints live emails to terminal).
# # Switch to SMTP backend in production.
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# # Platform host / Super Admin recipient
# PLATFORM_SUPER_ADMIN_EMAIL = os.getenv('PLATFORM_SUPER_ADMIN_EMAIL', 'umardaraz9056@gmail.com')
# DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'notifications@hausplatform.com')
# STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY', 'pk_test_51UN20T9PHak4iJQdZJdjIOtkcs5BwU3t0qurae0UGxSqtX18eV3BhLhkb2zCNOKXutyQA4jvYtlU8TYnWYpfBvKo004azqZACD')
# STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', 'sk_test_51UN20T9PHak4iJQdiKnU2yaqSO1io4EzgayozwJlg0taIPqRGWxOAm9Po5hGPdGhhSWjFUmU0huUtxbU9rer645J005ewhdHDr')
# STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', 'whsec_your_webhook_secret')

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-a40r9kz6nh74he3ygl9+to4vko3w1_k+#le^#!tohg4p*n3f=g'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []


# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',\
#     'memberships',
#     'scheduling',
#     'tenancy',
#     'rest_framework',
# ]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
#     'tenancy.middleware.TenantResolutionMiddleware',
# ]

# ROOT_URLCONF = 'haus_platform.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#                 'tenancy.context_processors.founding_slots_context',
#                 'tenancy.context_processors.user_portal_context',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'haus_platform.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# # Password validation
# # https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/6.1/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/6.1/howto/static-files/

# STATIC_URL = 'static/'


# # Email
# # https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# MAILERS = {
#     'default': {
#         'BACKEND': 'django.core.mail.backends.console.EmailBackend',
        
#     },
# }
"""
Django settings for haus_platform project.
"""

from pathlib import Path
import os

# Build paths inside the project: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-a40r9kz6nh74he3ygl9+to4vko3w1_k+#le^#!tohg4p*n3f=g'

DEBUG = True

ALLOWED_HOSTS = []

# haus_platform/settings.py


# Real Gmail SMTP Backend (Inbox delivery ke liye)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'umardaraz9056@gmail.com'  # Sender Gmail account
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'jvxudohliumseiup')  # Gmail App Password (NOT normal password)

# Platform Super Admin & Default Sender
PLATFORM_SUPER_ADMIN_EMAIL = 'umardaraz9056@gmail.com'
DEFAULT_FROM_EMAIL = f"Haus Platform <{EMAIL_HOST_USER}>"

# ==============================================================================
# STRIPE KEYS
# ==============================================================================
STRIPE_PUBLISHABLE_KEY = os.getenv(
    'STRIPE_PUBLISHABLE_KEY',
    'pk_test_51UN20T9PHak4iJQdZJdjIOtkcs5BwU3t0qurae0UGxSqtX18eV3BhLhkb2zCNOKXutyQA4jvYtlU8TYnWYpfBvKo004azqZACD'
)
STRIPE_SECRET_KEY = os.getenv(
    'STRIPE_SECRET_KEY',
    'sk_test_51UN20T9PHak4iJQdiKnU2yaqSO1io4EzgayozwJlg0taIPqRGWxOAm9Po5hGPdGhhSWjFUmU0huUtxbU9rer645J005ewhdHDr'
)
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', 'whsec_your_webhook_secret')


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'memberships',
    'scheduling',
    'tenancy',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'tenancy.middleware.TenantResolutionMiddleware',
]

ROOT_URLCONF = 'haus_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'tenancy.context_processors.founding_slots_context',
                'tenancy.context_processors.user_portal_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'haus_platform.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'