# Generated by Django 6.1.1 on 2026-09-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditledger',
            name='booking_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='creditledger',
            name='transaction_type',
            field=models.CharField(choices=[('grant', 'Grant'), ('spend', 'Spend'), ('refund', 'Refund')], default='spend', max_length=20),
        ),
    ]
