# Generated by Django 6.1.1 on 2026-09-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_creditledger_booking_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='inclusions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='standard_rate',
            field=models.DecimalField(decimal_places=2, default=199.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='tier_label',
            field=models.CharField(default='TIER 1', help_text='e.g. TIER 1, TIER 2, TIER 4 - EXECUTIVE', max_length=60),
        ),
    ]
