# Generated by Django 6.1.1 on 2026-09-30 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_membershipplan_inclusions_membershipplan_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberships.membershipplan'),
        ),
    ]
