# Generated by Django 6.1.1 on 2026-10-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_membershipplan_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending_deposit', 'Pending Admin Approval (Paid)'), ('unpaid', 'Payment Required (Unpaid)'), ('canceled', 'Canceled')], default='unpaid', max_length=20),
        ),
    ]
