# Generated by Django 6.1.1 on 2026-09-30 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='branding',
            field=models.JSONField(default=dict, help_text='Branding tokens: accent_color, accent_hover, primary_color, tagline, logo_url'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenancy.organization'),
        ),
    ]
