# Generated by Django 6.1.1 on 2026-09-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_alter_organization_branding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='founding_cap',
            field=models.PositiveIntegerField(default=100, help_text='Total available founding slots (Admin configured)'),
        ),
    ]
