# Generated by Django 6.1.1 on 2026-10-06 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0004_organization_founding_cap'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('plan_purchase', 'Plan Purchase Pending'), ('new_member', 'New Member Registered'), ('service_booked', 'Service Appointment Scheduled'), ('general', 'General Alert')], default='general', max_length=30)),
                ('target_tab', models.CharField(default='tab-overview', help_text='e.g. tab-approvals, tab-bookings, tab-members', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tenancy.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
