# Generated by Django 6.1.1 on 2026-10-07 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0007_remove_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenancy.organization'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('org_admin', 'Clinic Admin'), ('member', 'Patient'), ('doctor', 'Doctor'), ('receptionist', 'Receptionist')], default='member', max_length=20),
        ),
    ]
